### ISSUE TITLE
[Bug] Fuel resets when you use advance edit 

### ISSUE THREAD

**Issue by Lovis83854** [valheimPlus/ValheimPlus#112]
when you use advance edit on a torch or fire it will reset the fuel amount to 2 witch is default when you make a new one, if you have full fuel you will lose the extra fuel that was in there and you can use it to give yourself a torch/campfire with unlimited fuel by resetting it in that manner

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fuel resets when you use advance edit](https://trello.com/c/yIwBstol/4-fuel-resets-when-you-use-advance-edit)

**Comment by xiaodoudou** [comment]
The advance edit is tricky because it does reset all settings from an object.

For example:

- Ward ownership + permission is removed
- Portal lose its configuration
- Etc

From what I understand the call is doing: 
- HitPiece: Set it to null
- HitObject: Set it to null
`resetObjectInfo` from what I can read at [AdvancedEditingMode line 433](https://github.com/valheimPlus/ValheimPlus/blob/master/ValheimPlus/AdvancedEditingMode.cs)

Maybe some sub-properties are used in the GameObject which stores such data?

**Comment by xiaodoudou** [comment]
I have checked a bit more about the issue; seems not related to what I mentioned before in term of code.

Looks more that related to the fact that AdvancedEditing is creating a new object and destroying the old one.
It will a bit more complicated to handle.

In the case of a container, it does drop all items; but in other cases, it doesn't do anything special besides delete old, create a new one which will reset:

- Ward ownership, permission list
- Portal configuration
- Items stored inside such as fuel, coal, ...
- Etc...

This will need to get a full understanding of how a GameObject is storing properties and reassign if we want this to be fully "transparent".
