### ISSUE TITLE
[Feature Request] Display Server Message to all Players

### ISSUE THREAD

**Issue by lloesche** [valheimPlus/ValheimPlus#144]
Would be neat if there was a way to display messages to all players in game. Like "Server will update in 5 minutes" or something along those lines. A local socket would be great but maybe just a simple text file that can be created and is deleted once it's been displayed.
A fat message in the center of the screen would be ideal but just an entry in all players chat log, sort of like when a new player joins the server, would help already.

**Comment by Skrumpy** [comment]
Yes, this would be great.

**Comment by phatal808** [comment]
As an addition to this idea, it would also be nice to have a server login message welcoming and a few rules or notes.  Since Plus has near infinite possible playstyle settings, it would be nice to see what those settings are upon logging in to a server.  This idea is just a far fetched idea, I thought back in the day from Team Fortress mod that upon loading on to the server a built in web browser would show the community site for more information which could also be extensive details about server settings, rules, etc.

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under Server as "Display a message to all connected Players".
