### ISSUE TITLE
Sleeping Issue

### ISSUE THREAD

**Issue by Graghtok** [valheimPlus/ValheimPlus#170]
We’ve got a strange issue since installing Valheim Plus where the sleep timer seems to be different than the time of day. When it’s clearly nighttime, our characters just lay in  bed endlessly. We did modify the day and night length parameters in the config. Has anyone else experienced this? Not seeing much information out there.

**Comment by MiR4i** [comment]
I have not yet encountered that issue and I am altering the day/night cycle through V+, but just to be clear, every character currently playing on your server, regardless of their location in the world, is lying down at the same time?  In other words, if there are four active players on a server, then all four will need to be lying in a bed to "go to sleep" and pass through to the next day, otherwise your character(s) will just lie there and rest.

https://valheim.fandom.com/wiki/Day_and_Night_Cycle

While there are mods out there that can adjust the player threshold for sleep to occur and quickly pass through the night, V+ does not currently offer this option.

**Comment by Xaphanie** [comment]
We're having the same issue, night / sleeping occurs a long time after it's actually dark and when you wake up it's way into the next day so something is off for sure.

**Comment by xiaodoudou** [comment]
@Xaphanie did the time accelerated at least?

**Comment by xiaodoudou** [comment]
I do reproduce the issue when you are very close to the daytime.

**Comment by Graghtok** [comment]
Yes we've ensured that everyone is laying down at the same. 

Since sleeping isn't typically working for us, we're up all night in-game and the night cycles don't appear to be accelerated. Like Xaphanie noted, sometimes (when sleep does work) we wake up and it appears to be mid-day. 

Overall, not a not a deal breaker for us using the mod. Just a bit annoying to have to try to build during the middle of the night.

**Comment by WAR-Lust** [comment]
I have the same issue playing on dedicated server a friend made. I know he has modified the day/time cycles but so far the issue encountered where (i use a Clock mod to have the ingame time):

- My game was middle of the night (2am) and his was day time 
- Playing solo on the server: While lying in bed, sleep activate at different time (usually 00:00 but sometimes 8pm, 11pm or 2am) 

When sleeping the time is sped up and depending on activation wake up is between 4am and 11am

**Comment by babodad** [comment]
We are playing on a dedicated server and got the same issue. I did not change any of the time settings. If only one player is on the server sleeping does work. But with 2+ players everybody is just laying in their beds and nothing happens.

**Comment by nxPublic** [comment]
Should be resolved in 0.9.3
