### ISSUE TITLE
[Feature Request] Please fix broken server lag by editing k_ESteamNetworkingConfig_SendBufferSize!!

### ISSUE THREAD

**Issue by astranberg** [valheimPlus/ValheimPlus#189]
Hello all,

Ever since Valheim 0.146.8 servers are unplayable again. You know the drill: doors don't open, chests don't open, you can't see your friend, buildings don't spawn in. The previously implemented trick of increase send/receive rate on assembly_valheim.dll no longer fixes the issue. There is now another issue: buffer size.

It's set to a measly 9 kb. Not sure what it used to be. Increasing it to even 18 makes a big difference.

Thank you all for what you've been doing!

**Comment by xiaodoudou** [comment]
Hi @astranberg,

The dataRate is acting on the max value that the client/server is allowed to go over the default value.
This is configurable on the [Server] section. Note the server and client need to have both values adjusted and worth having a normal value. If your bandwidth is limited, you should not try to go other it especially if you are on server mode: p2p (not dedicated).

On another note, the new version of the game did disable Nagle's algorithm, this network algorithm does act as:

```
if there is new data to send then
    if the window size ≥ MSS and available data is ≥ MSS then
        send complete MSS segment now
    else
        if there are unconfirmed data still in the pipe then
            enqueue data in the buffer until an acknowledgment is received
        else
            send data immediately
        end if
    end if
end if
```

By experience, it depends on your internet to have such an algorithm enabled or not.
I tend to disable it on my PC itself because I'm lucky enough to have good bandwidth and good home network equipment.

People at the moment complain that disabling it bottleneck their internets; looks like more a p2p issue from my point of view as this algorithm is there for avoiding queueing outdated data.

There is a plugin that does the work on that:
https://github.com/rumangerst/valheim-reeenable-nagle

On another angle, the value you are pointing to is Steamworks.ESteamNetworkingConfigValue.k_ESteamNetworkingConfig_SendBufferSize

Base on steam documentation (https://partner.steamgames.com/doc/api/ISteamNetworkingSockets) it is part of their SDK but I'm not sure Valheim utilizes it besides the server listing which would make sense to be a low value.

When you are in-game and having such an issue, you should check the debug pannel (F2), which you can see how much data exchange recv/sent and the quality of your network (if you have some packet lost). 

Such issues for me did happen in such scenario:

- 2 players on a dedicated server when the dataRate was default and a lot of stuff happening inside a big complex base
- 3 players on a dedicated server when one of the players is having 300ms of latency

Would advise checking these aspects on your side:

- V+ dataRate (something like 120 which means 120kb/s up/down exchange)
- If you are in P2P, ensure the best connection is hosting the server, as it commits the changes on the World owner
- If you are on a dedicated server, ensure ping is good enough for you and your friends, test its network burst rate
- Test if the plugin that enables Nagle's algorithm, help you

Cheers,

**Comment by astranberg** [comment]
I have a dedicated server with ping of 24, data rate set to 1000, and didn't have any issues until 0.146.(0.8-11) update.
Re-enabling Nagle's algorithm seems to have worked.
Would be nice for this option in V+.

Thx!

**Comment by fant0mas9** [comment]
The person who's github that is has stated in the comments of their mod - 

"...the Valheim devs accidentally routed all traffic (including dedicated servers and local players) through Stream and this causes a lot of issues. I think there was a beta patch that fixes this issue until the next patch comes out (likely this week)."

So may be worth holding off on coding for this until see what the patch does to networking. Note, I've not been able to find any info on the beta patch or comments from devs to confirm this stmt as yet.

**Comment by astranberg** [comment]
@fant0mas9  link?

**Comment by fant0mas9** [comment]
https://forums.nexusmods.com/index.php?/topic/9709058-remove-network-overload/page-2#entry91268518

**Comment by nxPublic** [comment]
This is a steam API limitation.

Don't set your dataRate above 240 if you don't know or are uncertain on what you are doing.
