### ISSUE TITLE
Global Mod Enable/Disable

### ISSUE THREAD

**Issue by fustilarian01** [valheimPlus/ValheimPlus#190]
It would be nice to have a global enable/disable option in the config file. It would allow you to play one character with the mod features enabled and another with everything disabled. I thought about making a copy of the config file that would have everything disabled and switching back and forth between the custom and the default config files, but having a global enabled/disabled variable would be a lot easier. :)

Thanks!

**Comment by ShammyLevva** [comment]
You would still have to manually edit the file each time you switched worlds. 

Instead I'd suggest a Active Servers Setting that listed the servers the mod is active for. eg:

[Active Servers]
default = true
1234567890 = true
2345678901 = false
....

If the server is in the list the mod is on or off according to true/false, if the server is not in the list what ever the default settings is determines if mod is on or off. This gives exactly what you are after without having to edit the file every time you switch servers.

**Comment by radmint** [comment]
@fustilarian01 I'm not sure we could make this work with the latest configuration update. We automatically update the configuration of any client joining a server with V+ enabled to have the same configurations so that configuration would come from the server that you're joining. Right now, we recommend that people rename their `Valheim/winhttp.dll` to `Valheim/winhttp.dll.disabled` in order to disable the mod on servers that don't have it.

I agree that we need functionality to switch configurations be more flexible, but our current state is a stepping stone to that point.
