### ISSUE TITLE
[Feature Request] Crop notifier when crops too close when placing

### ISSUE THREAD

**Issue by Jeffrey2457** [valheimPlus/ValheimPlus#28]
Such as when using cultivator to place crops, if they're too close together, tinting the crop yellow to signify that it's too close to another, or a GUI stating that they're too close together

**Comment by Samsterious** [comment]
Placing plants currently is a trial-and-error exercise, and since there's no way to recover freshly-planted seeds you're forced to either wait two whole harvests to try again or dispose of the plant and take the loss, which is very difficult to justify when you've just found your first handful of seeds. This would definitely be a major quality of life feature.

Alternatively, add a configuration that disables crop density checks entirely, or allows users to change the distance required.

**Comment by radmint** [comment]
This feature has been included in the current release. Thank you for the suggestion!
