### ISSUE TITLE
[BUG] Default config damage scaling too high?

### ISSUE THREAD

**Issue by EchoingZen** [valheimPlus/ValheimPlus#281]
- **OS:** Windows Client
- **Valheim Game Version:** 0.147.3
- **V+ Mod Version:** 0.9.4

**Describe the bug**

The default valheim_plus.cfg file has the following entry:
`gameDifficultyDamageScale=0.4`
This would be a 40% additional damage bonus instead of the vanilla game's 4%, ten times the intended damage.
I believe it should instead read:
`gameDifficultyDamageScale=0.04`

**This might be an intended change, I'm not sure.**

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Download the Windows Client of Valheim Plus
2. Open the valheim_plus.cfg file
3. Look at the line with gameDifficultyDamageScale

**Expected behavior**

By default, additional players should increase monster damage by 4%, not 40%

**Troubleshooting**

Modified the config to match the 4%, for our server.

**Screenshots**

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:** https://pastebin.com/7bcJMRT7

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.
N/A

**Comment by shilliash** [comment]
It seems to be intended - and you are absolutely correct with those numbers it is 10x more than vanilla per extra player. 
We've tested it carefuly and it should be modified (scaled down) otherwise Furlings are way to overpowered for group of 3 (because they do get boost of 3x 40% dmg and 3x40% HP. 
If one is using "fake extra player" it makes it even more difficult. 

PS. default 4% (vanilla servers) is way to little - in end game gear they are kind of easy, from another hand 40% can be to much. 
Try our  settings it seems to work well for groups of 2-3-4 

gameDifficultyDamageScale=0.15
gameDifficultyHealthScale=0.6
extraPlayerCountNearby=1
setFixedPlayerCountTo=0
difficultyScaleRange=200

**Comment by EchoingZen** [comment]
Yeah, typically its unwise to scale damage too high per player, as it will quickly overwhelm block power or armor. The best place for difficulty scaling would be the armor, shields or mobs themselves.

I was just reporting it since I believe the intent was to have a framework that others can work off of, so figured they'd want the default config to be as vanilla as possible.

That being said, for our server, we had set it to always be 4 players @ 4% and since we play permadeath, it seemed about right.
