### ISSUE TITLE
[FEATURE REQUEST] Clear distinction between server and client settings

### ISSUE THREAD

**Issue by ocgineer** [valheimPlus/ValheimPlus#282]
At the moment there is only one config file for both server and client settings, it would be something to have them separated or have a clear distinction between them to indicate what is synced/enforced from the server if serverSyncsConfig is enabled.

For example, the server settings would have options like `allowAdvancedBuildingMode` and `allowAdvancedEditingMode` to indicate to the clients that these features are allowed and enabled. And then clients themself can enable these modes themself if they want to use them and set their own hotkeys, instead of being enforced by the server config with sync enabled.

**Comment by nxPublic** [comment]
I like the idea but its straight up not going to be used by most likely more than 90% of the users. I also think most people wouldn't be able to quite understand how it works.

We already have difficulties conveying how the current system works and this would make things more complicated and cost quite some time to implement in comparison to the amount of "gain" from it.

We had a similar system like this once and it didn't work out at all, that's why enforceConfiguration is gone now.

**Comment by mdcohen** [comment]
Can you shut the eff up please? It’s well after midnight. Go to sleep.
Thanks.
