### ISSUE TITLE
[Feature Request] config file handling

### ISSUE THREAD

**Issue by mattyteds** [valheimPlus/ValheimPlus#288]
**Is your feature request related to a problem? If so, please describe.**
Unless I'm missing something it appears anytime there is an update to the mod I have to replace and reconfigure the config file. Yet other mods I use not only just merge in new options. Other mods also create a default config file, V+ just reports and error that it failed to find a config file.

**Describe the solution you'd like**
Merge the new config options into the existing config file.

*NOTE*
When I click the button for a feature request your github template still adds the [BUG] tag to the title, defeating the purpose of having an option of Bug or Feature Request.

**Comment by dubl3a** [comment]
I just got hit by this.  My dedicated server users, after an update, reported everything was back to default.  I use AMP to run my servers and when it updates, it just pulls the ZIP and overwrites all files.  Lots of inventory was lost because of storage returning to normal sized!

Configuration file needs to be a .example moving forward.
