### ISSUE TITLE
[BUG] StaminaUsage options doing nothing

### ISSUE THREAD

**Issue by mattyteds** [valheimPlus/ValheimPlus#290]
- **OS:** Linux Server
- **Valheim Game Version:** 0.147.3
- **V+ Mod Version:** 0.9.4

**Describe the bug**

I can set cultivator or hoe to -100 or even -1000 and they still use the same amount of stamina in game.
Yes it is enabled,

**Expected behavior**

As the config says "Each of these values modifies the stamina drain by %."

**Troubleshooting**

I tried setting them to both -100 and 100 and the amount used is the same.

**Comment by radmint** [comment]
This will be fixed in the next release

**Comment by SiniestroO** [comment]
i had this problem, but the problem its not what you think, and the solution is simple.... there's a syntax error in you cfg file and you will most likely never find it, this makes some options not to function properly and if you have several errors almost all things won't work, so you need to download the mod again and extract the original cfg file from there and do it all over again with your preferences, its important that you don't copy from the old file text and paste in to the new one, just edit the file individually as if it where for a new setup....

this i'm sure its because all the updates modify the cfg file and it corrupts over time (all by our hands). the solution should implemente a "sample cfg" or a way to export the old data to the new cfg file... how? no idea, maybe adding in the changelog exactly where new strings are added so we can paste that string in the current cfg being used... maybe.

cheers.

**Comment by mattyteds** [comment]
@SiniestroO this occurs with a fresh config, as stated only effects some tools, and is a know issue that's being worked on. If it was syntex issue I'd have more problems then this.

**Comment by SiniestroO** [comment]
> @SiniestroO this occurs with a fresh config, as stated only effects some tools, and is a know issue that's being worked on. If it was syntex issue I'd have more problems then this. Also the config file is pretty small and well layed out, it would be pretty easy to find a issue.

oh, ok... sorry i was having the exact same issue and i resolved it like i mentioned and its working as intended.... i hope they can fix this, cheers!

**Comment by smellord** [comment]
@SiniestroO i've let the mod generate a completely fresh config file and i still have the issue.. it was working before updating to 0.9.4.
Which Version are you on?

I also have the right value in the logs. so that cant be the case.. it loads correctly but it has no changes in game.
[Info   : Unity Log] 03/09/2021 20:45:59: CONFIGDATA: jumpStaminaDrain=0

**Comment by SiniestroO** [comment]
> @SiniestroO i've let the mod generate a completely fresh config file and i still have the issue.. it was working before updating to 0.9.4.
> Which Version are you on?
> 
> I also have the right value in the logs. so that cant be the case.. it loads correctly but it has no changes in game.
> [Info : Unity Log] 03/09/2021 20:45:59: CONFIGDATA: jumpStaminaDrain=0

the same version, mine was that, a syntax error somewhere... not only the stamina drain option didn't work also the item restriction for the portal for example....my solution was download the latest mod and re do the entire cfg by hand

**Comment by nxPublic** [comment]
All of you constantly talk about your Config files without posting them to http://pastebin.com.

How are we supposed to help you if you don't post your config files.

**Comment by alarteaga** [comment]
I think this is still working, but the numbers you need to add changed. When I created my server in g-portal, the values for these options were something like 10, so to increase my stamina I changed it to 5 and it was all working fine. I got the same issue as the people below so when I looked at the file you get directly from here it tell you to basically use a percentage so I switched the values to =50 and that seems to have fixed it.

**Comment by mattyteds** [comment]
This was fixed with the latest release. Please stop posting here, create a new report if you have an issue.
