### ISSUE TITLE
[BUG] Weight allowance is not following config value

### ISSUE THREAD

**Issue by Zxurian** [valheimPlus/ValheimPlus#354]
- **OS:** Ubuntu 20.04 LTS / Windows 10
- **Valheim Game Version:** `0.147.3`
- **V+ Mod Version:** `0.9.5`

**Describe the bug**

Weight allowance with Megingjord buff is being increased by 300, despite config file having
```
[Player]

; Change false to true to enable this section
enabled=true

; The base amount of carry weight of your character
baseMaximumWeight=300

; Increase the buff you receive to your carry weight from Megingjord's girdle
baseMegingjordBuff=150
```

**To Reproduce**

Overlay new V+ `0.9.5`, over existing `0.9.4`. After starting server, and joining immediately saw weight allowance was at 600.

**Expected behavior**

Weight allowance should be at 450 per the config value.

**Troubleshooting**

Check config file on both unix server and windows client, both have the same value as described above. When in game, still shows weight value at 600. Tried unequipping and re-equipping, no change.

**Screenshots**

n/a

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**
https://pastebin.com/Gyq2U3ED

**Additional context**

no other mods

**Comment by ShammyLevva** [comment]
From testing it seems that it is doubling the value of baseMegingjordBuff

**Comment by healiha** [comment]
I can't submit a PR right now but this is due to this line
https://github.com/valheimPlus/ValheimPlus/blob/b5077d10e4840d0271f7797e8c952d99633734e2/ValheimPlus/GameClasses/Player.cs#L148

Instead of _setting_ the actual amount the belt gives, it increase/decrease the value of the buff.

As I see it `baseMegingjordBuff` should be renamed to something like `megingjordBuffIncrease` to match the actual way it works.
