### ISSUE TITLE
[FEATURE REQUEST] Update management

### ISSUE THREAD

**Issue by BroderickCarlin** [valheimPlus/ValheimPlus#453]
One of the current pain points of running a modded server and requiring all players to also have the mod installed is assisting players with updating the mod when a new version rolls out. Given the open source aspect of the project it should be feasible to add in an update management system to allow the mod to either auto-update or prompt the user to update without the need to manually download and copy/paste files. 

An initial MVP of such a new feature could start as just providing the option to auto-update or not. Future milestones could potentially include: 
- The ability to peg to specific releases
- The ability to automatically match the local mod version to a server's version upon connection
- The ability to disable the mod if connecting to a vanilla server

**Comment by Voarexxx** [comment]
I actually currently have a working .sh script that allows you to automagically summon the wizards to update to Valheim Plus latest WindowsClient.Zip release. I am working out a few kinks currently due to the most recent update I'm not sure what the error is, but here is the link to my code. https://github.com/Voarexxx/valheim_plus_client_update_tool

**Comment by Voarexxx** [comment]
> One of the current pain points of running a modded server and requiring all players to also have the mod installed is assisting players with updating the mod when a new version rolls out. Given the open source aspect of the project it should be feasible to add in an update management system to allow the mod to either auto-update or prompt the user to update without the need to manually download and copy/paste files.
> 
> An initial MVP of such a new feature could start as just providing the option to auto-update or not. Future milestones could potentially include:
> 
> * The ability to peg to specific releases
> * The ability to automatically match the local mod version to a server's version upon connection
> * The ability to disable the mod if connecting to a vanilla server

.sh script. 
https://github.com/Voarexxx/valheim_plus_client_update_tool

**Comment by Mixone-FinallyHere** [comment]
For the mod to update the game must close

Mods in this game work at launch of game due to lack of game support of mod

The game has no way of inserting a mod at runtime so it would require fairly complex instance management to be even able to think about doing this in-mod

Given how simple it is to update the mod and that there exist sidemanagement projects that can be used means adding this to the actual mod itself is an amount of work that is unnecessary and a waste of effort given how simple the solution is.

If the game ever does support mods this would be something to look into, but given the EA state of the game, such a system will be VERY costly in terms of time and provide virtually no benefit to existing systems.

**Comment by Voarexxx** [comment]
> For the mod to update the game must close
> 
> Mods in this game work at launch of game due to lack of game support of mod
> 
> The game has no way of inserting a mod at runtime so it would require fairly complex instance management to be even able to think about doing this in-mod
> 
> Given how simple it is to update the mod and that there exist sidemanagement projects that can be used means adding this to the actual mod itself is an amount of work that is unnecessary and a waste of effort given how simple the solution is.
> 
> If the game ever does support mods this would be something to look into, but given the EA state of the game, such a system will be VERY costly in terms of time and provide virtually no benefit to existing systems.

^ I have done the things in a powershell. I even included a new option to choose the placement and into which folder you'd like the update to go into.
.sh script.
https://github.com/Voarexxx/valheim_plus_client_update_tool

This automagically summons the wizards to update to the latest Valheim Plus. So please feel free to hand it out! It took a LOT of time making this script. Let me know if you have any additions or feedback for it!
