### ISSUE TITLE
[FEATURE REQUEST] Add Onions to pickables config please.

### ISSUE THREAD

**Issue by OverkillEngine2021** [valheimPlus/ValheimPlus#636]
Seems odd to leave them out.

**Comment by nxPublic** [comment]
It was not a conscious decision, they have been added with H&H. I added it to my list of things todo for 0.9.9.1

**Comment by OverkillEngine2021** [comment]
Awesome, thanks!

**Comment by DrunkTaank** [comment]
_Any chance this is still on the radar?  I'm wondering if this is a bigger issue, as even Terraheim has had issues with the onion._

I apologize, as I now realize that this was fixed in an update to the files Pickable.cs.  What is strange to me, is that I'm running the latest stable release, but that is from Sept 17.  Should this be working?  Or do I need to update to a beta release?

**Comment by JF10R** [comment]
@DrunkTaank I believe they were added with [V+ 0.9.9.5 release](https://github.com/valheimPlus/ValheimPlus/releases/tag/0.9.9.5) a few days after your comment. This issue should be resolved now.
