### ISSUE TITLE
[Feature Request] 3 bronze ingots from 3 tin and copper ingots

### ISSUE THREAD

**Issue by Corwin616** [valheimPlus/ValheimPlus#67]
I consider it a mistake that mixing, for example, 3 kilograms of different metals, the output is only 1 kilogram
I would like to be able to configure this parameter

**Comment by astranberg** [comment]
If accuracy is your goal, this may interest you [ref: [wikipedia](https://en.wikipedia.org/wiki/Bronze#cite_note-13)]
`There are many different bronze alloys, but typically modern bronze is 88% copper and 12% tin`

In which case you would want 1 tin per 8 copper.

If you wanted to actually implement this, it would require balancing such that copper would drop much more frequently, forges would be quicker, and the weight of copper and tin be adjusted.

**Comment by crwitt** [comment]
Or, to keep it simple, fix five: 1 tin + 2 copper = 3 bronze.

**Comment by astranberg** [comment]
Better yet, make it configurable.

Could even be expanded to other recipes

**Comment by Corwin616** [comment]
i found mod https://www.nexusmods.com/valheim/mods/94

**Comment by Mixone-FinallyHere** [comment]
Cool that a mod does that!

It does not make sense to me, physically or gamewise, because you have 3 components does not necessarily mean you get 3 outputs, you don't get two axes from 1 stone + 1 wood ^^

This wont be implemented but you are more than welcome to use that mod.

If you encounter mod conflicts please ask the mod author to contact us if necessary to sort them out.

I am closing this issue.
