### ISSUE TITLE
[BUG] Creature Level And Loot Control recent update not compatible with Valheim Plus

### ISSUE THREAD

**Issue by bigreefer** [valheimPlus/ValheimPlus#775]
- **OS:** [Windows]
- **Valheim Game Version:** [0.212.9]
- **V+ Mod Version:** [9.9.11]

**Describe the bug**

Creature Level And Loot Control 4.5.4 not compatible with Valheim Plus 9.9.11

**To Reproduce**

Steps for the devs to reproduce the behavior:
Download most recent version of Creature Level And Loot Control and Valheim Plus

**Comment by stolenvw** [comment]
Compatibility issues are not a bug, all off Smoothbrain's mods will tell you they are not compatible with V+

**Comment by bigreefer** [comment]
It was compatible until now though, also it says that this mod should be mostly compatible in the description of Valheim Plus and doesnt say anywhere on Creature Level And Loot Control thunderstore page that its not compatible, so idk about that bud

**Comment by Grantapher** [comment]
I'm not really involved, but there is some ongoing issues between that repository's dev and the valheim plus project: [bug](https://github.com/blaxxun-boop/PassivePowers/issues/5)

**Comment by bigreefer** [comment]
Shucks... Hopefully since they both rely on BepInEx it will be easier to find what new conflicts arose in the recent update of Creature Level And Loot Control

**Comment by alundil** [comment]
I suspect this isn't going to resolveable by valheim plus. If Smoothbrain, the dev, is building their mods now purposefully to be incompatible with V+, then that is, as they say, that.

This is unfortunate, to say the least, but seems mainly a failure of communication and expectations.

**Comment by bigreefer** [comment]
One of the devs on V+ said they were working on cleaning up the V+ code because of it's notorious incompatibility issues... so hopefully that happens!

**Comment by psyferre** [comment]
@bigreefer, that's a nice thought, but I tried.  Smoothbrain/blaxxun-boop has no interest in compatibility and is actively working against it.  https://github.com/blaxxun-boop/Groups/issues/13

**Comment by bigreefer** [comment]
@psyferre Yeah I just saw all that drama... it's a shame for the valheim community and seems really unnecessary tbh

**Comment by G4ming69** [comment]
> Compatibility issues are not a bug, all off Smoothbrain's mods will tell you they are not compatible with V+

yeah what a shitty mod developer! other versions were always ok! gj

**Comment by GraveofBears** [comment]
The good news is that more compatible mods are being developed that do the exact same thing as V+, these "modular" versions will be much easier to maintain and keep compatibility with other mods. So even if a mod is conflicting with V+, we wont be adding any conflicts to the modular QoL mods.

**Comment by SSimp258** [comment]
> The good news is that more compatible mods are being developed that do the exact same thing as V+, these "modular" versions will be much easier to maintain and keep compatibility with other mods. So even if a mod is conflicting with V+, we wont be adding any conflicts to the modular QoL mods.

Only problem with this is you'll need "x" amount of mods to fully replace V+ which means even more memory used when loading those mods. You also increase the chances of memory leaks and potential incompatible errors because you now have 20 mods vs 1 or 2 mods. 20 mods trying to change 1 memory location is bad vs 2 mods. Or for those that only use V+, you just have 1 mod that does what you want. You'll also have to keep those 20 mods updated by yourself or a mod manager which 90% of the time, those mod managers screw up. 90% of the help requests i handle on discord are mod manager issues.

**Comment by GraveofBears** [comment]
That is actually backwards, I know that sounds weird, you would think that 20 mods use more memory than 1 however it depends on what that mod is doing. If that mod is changing 20 things using the same methods as the 20 mods than performance will be the same. There really isn't any difference.

Now, say that 1 of those 20 things in your 1 mod break after an update, you're stuck with being waiting, most the time several weeks for an update.
Where if you have 20 mods doing their own things you might just need to remove one mod to continue playing. It's usually easier for us to update one small mod than a huge overhead mod.

**Comment by SSimp258** [comment]
@GraveofBears For some reason your reply isn't showing on here but i got it in my email and it's on the discord but here goes.

V+ is like 4MB of HD space(which HD space is memory). So that means all the mods you need to download should be equal or less than V+ size. Which some might be but if you're downloading say 20 mods to replace V+ fully (might be a stretch, might not be, idk for sure) but I would almost guarantee you that you'd have way more than 4MB of HD space used by those mods unless they are bare bones mods that they only replace V+ sections but i'm going to doubt that.

I also made some visual representation of what I was referring to as far as memory. I'll upload them at the bottom. But you can have memory conflicts kinda like Better Archery when we tell ppl to turn off the quiver to make things work between Better Archery and V+. The game doesn't like it when 2 mods are trying to make changes to the same memory locations. If the game does allow both mods to control 1 memory location, you can cause huge problems or even memory leaks can happen. You can also get FPS drop if 2 mods are trying to control a hearth for example or both mods are trying to control the particles from the hearth and so on.

When i went through my software dev classes, we were taught that having more than 1 program doing things causes an exponential increase in possible issues between those programs. It's no different for games and their mods. 1 mod is less likely to have issues than 20 mods. Mainly because that 1 mod will not have any potential incompatibilities between other mods since there isn't any other mods.

Now, take those 20 mods and you've now increased the potential for incompatibilities between them on top of compounding the amount of memory you need for those 20 mods. Memory is both HD space and the amount of RAM, GPU or System, needed for them. Also, Mod 1 might have issues with Mod 5 which has issues with Mod 15 which has issues with Mod 2 and so on. This is why it compounds exponentially.

I forgot to mention this is why we have had ppl come into the discord and ask why they can only have around 5 ppl on their server at a given time. When i asked how many mods were they running, they would tell me 120+ mods. That's a lot of issues between the mods and even between the main game itself and a ton of memory going to those mods which could be freed up for more than 5 players on their server. Hopefully, now it all makes sense. But, on the flip side, if it's just replacing V+ sections and nothing else in those mods, those 20 mods would take up the same or maybe smaller amount of RAM than V+.

Pics below here (i think). Also, sorry but i used paint to quickly do it.
![mem usage multi](https://user-images.githubusercontent.com/96361739/220995149-1bd382d3-33d4-430f-bb9c-d633c1194495.png)
![mem usage](https://user-images.githubusercontent.com/96361739/220995153-3d25059b-e5d7-465b-99f4-4cf4b27f9c1f.png)
