### ISSUE TITLE
Error joining server.

### ISSUE THREAD

**Issue by Solence1** [valheimPlus/ValheimPlus#92]
Probably a stupid question but ill try it anyway. Me and my friend wanted to use ValheimPlus to share map progress. We both installed it and had the same config. Wen he tries to join my server he gets an error which says the server is running on a different version. Did we do something wrong or whats the issue?

**Comment by nickkeane** [comment]
@Solence1 

Edit:
If you can join the server but they can't, it's probably on their end. Tell your friend to hit player log button in the main menu and look in his player log for a hash. Then, check the server logs for a hash and compare them. 1st part is Valheim version, 2nd part is V+ version, 3rd part is cfg hash. They all need to be identical.

I'm having the same issue (with an edited config), and looking into what's going on w/ my server with the latest stable 0.8.5.

Looking at the code, it looks like the hash is done only against the Configuration.Current, meaning the file should already be imported, meaning file line endings and spaces shouldn't be an issue w/ the hash (in theory). Maybe triple-check spaces at the end of INI values? (just in case there's a difference)

How are you hosting the server? I'm using https://github.com/mbround18/valheim-docker in Docker.

It could also be that there's differences between the 0.8.5 generated artifacts.

This is my first hunch, since I'm copying an otherwise identical .cfg file over to my server via WinSCP from Windows to Linux. It should be a binary copy :/. And the code below is hashing from the imported Config structure, not the .cfg file itself, so it shouldn't even matter.

```
string gameVersion = Version.CombineVersion(global::Version.m_major, global::Version.m_minor, global::Version.m_patch);
__result = gameVersion;

Debug.Log($"Version generator started.");
if (Configuration.Current.Server.IsEnabled)
{
    if (Configuration.Current.Server.enforceConfiguration && Configuration.Current.Server.enforceMod)
    {
        __result = gameVersion + "@" + ValheimPlusPlugin.version + "@" + ConfigurationExtra.GetServerHashFor(Configuration.Current);
        Debug.Log($"Version generated with enforced mod and config hash : {__result}");
        return false;
    }

    if (Configuration.Current.Server.enforceMod)
    {
        Debug.Log($"Version generated with enforced mod : {__result}");
        __result = gameVersion + "@" + ValheimPlusPlugin.version;
        return false;
    }
}

Debug.Log($"Version generated : {__result}");
return false;
```

If you click player.log button in the main menu and open player.log, there should be some lines showing a hash value, generated from the code above. Likewise, your server logs should have a similar hash value printout.

Client Hash: 0.145.6@0.8.5@6BF0C498747C15D9723361A86229713C
Server Hash: 0.145.6@0.8.5@6BF0C498747C15D9723361A86229713C (Edit: Hey, looks like a clean reinstall of both client and server did the trick? Probably some weird spacing/newline issue, i didn't change the cfg)
My Config: https://drive.google.com/file/d/1Tqsx66wDhDA2N9sr2hMwipz4ellhpO5X/view?usp=sharing

Server w/ (Mostly) Default Cfg Hash: 0.145.6@0.8.5@D41D8CD98F00B204E9800998ECF8427E
If you enable only server, enforceConfiguration, enforceMod, the above hash is what "should" show up. I don't know if it's correct.

Presumably the above hash should be uniform for everyone up to date w/ v0.8.5 using what's in the artifacts, granted they only change 

@nxPublic 

Is the D41D hash above the correct hash for a default server config with only [Server] enabled=true and enforceConfiguration=true modified?

You guys may want to set up a function to scrub the configs that use string values of spaces, newline characters, and any other special characters that could cause issues immediately prior to a hash calc, just in case. Or maybe a debug printout of config settings that the mod didn't match or were missing on one side, for an inefficient "hard" compare (if possible).

Also, make sure the Windows/Linux 0.8.5 artifacts are hash unified. Not sure if there could be a hash issue even there, I'm not operating off the default cfg.

Also, change the code please such that a "VVersion@V+Version@Hash" is always printed out in the player/server logs, even if the [Server] enabled, enforceConfiguration, enforceMod isn't set, b/c i can't get a true baseline .cfg hash currently, since I have to change those settings to get it to print. Or, exclude those 3 config options from hashing. Would also be a good idea to print out a default config hash in the Github release notes when doing a release.

Also, on a semi-unrelated note, it looks like disable password isn't working for me. I have:

>[Server]
>enabled=true
>disableServerPassword=true

in the Google Drive config, but it still shows the key/lock symbol and still requests a password...

**Comment by nxPublic** [comment]
0.8.6 should resolve any issues in this area.

Please create a new issue if you encounter the same problem after its release later today.
